# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='autor',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='catagory',
            new_name='category',
        ),
    ]
